### ISSUE TITLE
Please make sure all images included in the model for the production variant variant-1 exist, and that the execution role used to create the model has permissions to access them.

### ISSUE THREAD

**Issue by vrathore18** [yuyasugano/terraform-sagemaker-sample-1#1]
I used the same IAM module present in the project but I am getting the below error when I am creating an endpoint:

`Please make sure all images included in the model for the production variant variant-1 exist, and that the execution role used to create the model has permissions to access them.`

Any idea how to fix this?

**Comment by yuyasugano** [comment]
I understand that you faced this error when it was creating an endpoint (inference right?). Where did you see this error? On your Jupyter Notebook? Terraform was run but only running the notebook until the end failed? Is my understanding correct? I could do just a quick search today and it may be either 1) the used image (container) was not accessible or 2) the given role did not have an access to the image. @vrathore18

**Comment by yuyasugano** [comment]
> I used the same IAM module present in the project but I am getting the below error when I am creating an endpoint:
> 
> `Please make sure all images included in the model for the production variant variant-1 exist, and that the execution role used to create the model has permissions to access them.`
> 
> Any idea how to fix this?

I understand that you faced this error when it was creating an endpoint (inference right?). Where did you see this error? On your Jupyter Notebook? Terraform was run but only running the notebook until the end failed? Is my understanding correct? I could do just a quick search today and it may be either 1) the used image (container) was not accessible or 2) the given role did not have an access to the image. @vrathore18
